// Prodotti importati dai feed di affiliazione (CJ Affiliate: Notino.it, Marionnaud IT).
// Generato da una selezione curata: titolo, prezzo, immagine e link vengono dal feed;
// i tag per il test (skinTypes, concerns, ...) sono assegnati a mano in base alla funzione
// dichiarata del prodotto. linkPending: true finché il merchant non approva l'account —
// fino ad allora affiliateUrl punta alla pagina prodotto senza tracciamento.

import type { Product } from './products';

export const FEED_PRODUCTS: Product[] = [
  {
    id: "nt-cerave-hydrating-cleanser",
    name: "Hydrating Cleanser",
    brand: "CeraVe",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 14.19,
    description: "Emulsione detergente effetto idratante (473 ml)",
    affiliateUrl: "https://www.notino.it/cerave/cleansers-emulsione-detergente-effetto-idratante/p-15692412/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cerave/3337875597333_01-o__5.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CEVCLSW_KECL20",
    skinTypes: ["secca", "normale", "sensibile"],
    concerns: ["idratazione", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cerave-blemish-control-cleanser",
    name: "Blemish Control Cleanser",
    brand: "CeraVe",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 11.73,
    description: "Gel detergente contro le imperfezioni della pelle acneica (236 ml)",
    affiliateUrl: "https://www.notino.it/cerave/cleansers-gel-detergente-contro-le-imperfezioni-della-pelle-acneica/p-16139497/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cerave/3337875784054_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CEVGBGW_KCLG02",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "pori-dilatati"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-la-roche-posay-effaclar-supramolecular-g",
    name: "Effaclar Supramolecular Gel Detergente",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 11.81,
    description: "Gel detergente contro la pelle lucida e i pori dilatati (200 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/effaclar-supramolecular-gel-detergente-contro-la-pelle-lucida-e-i-pori-dilatati/p-16392040/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875958738_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPVJCT_CACV00",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "pori-dilatati"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-la-roche-posay-toleriane-gel-detergente",
    name: "Toleriane Gel Detergente",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: false,
    price: 19.63,
    description: "Gel detergente in schiuma per pelli sensibili (400 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/toleriane-gel-detergente-in-schiuma-per-pelli-sensibili/p-16203221/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875545822_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPTOLW_KCLG84",
    skinTypes: ["sensibile", "secca", "normale"],
    concerns: ["rossori-sensibilita", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-la-roche-posay-physiologique-ultra",
    name: "Physiologique Ultra",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: false,
    price: 17.17,
    description: "Acqua micellare per pelli molto sensibili (400 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/physiologique-ultra-acqua-micellare-per-pelli-molto-sensibili/p-604575/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875528108_01-o__16.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPPHUW_KMUR15",
    skinTypes: ["sensibile", "secca", "normale", "mista", "grassa"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-tolerance-extremely-gentle-cleanse",
    name: "Tolérance Extremely Gentle Cleanser",
    brand: "Avène",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 12.83,
    description: "Latte struccante detergente (200 ml)",
    affiliateUrl: "https://www.notino.it/avene/tolerance-latte-struccante-detergente/p-16076892/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770142280_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVETOLW_KBOL10",
    skinTypes: ["sensibile", "secca"],
    concerns: ["rossori-sensibilita", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-cleanance-acqua-micellare",
    name: "Cleanance Acqua Micellare",
    brand: "Avène",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 13.77,
    description: "Acqua micellare per pelli grasse e miste (400 ml)",
    affiliateUrl: "https://www.notino.it/avene/cleanance-acqua-micellare-per-pelli-grasse-e-miste/p-16254335/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770390315_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVECLEW_KMUR01",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-xeracalm-olio-detergente",
    name: "XeraCalm Olio Detergente",
    brand: "Avène",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: false,
    price: 22.18,
    description: "Olio detergente per pelli secche (1000 ml)",
    affiliateUrl: "https://www.notino.it/avene/xeracalm-olio-detergente-per-pelli-secche/p-16389696/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282771000299_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVEGVOV_YCSV03",
    skinTypes: ["secca", "sensibile"],
    concerns: ["barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-sensibio-gel-moussant",
    name: "Sensibio Gel Moussant",
    brand: "Bioderma",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: false,
    price: 18.61,
    description: "Gel detergente delicato lenitivo e struccante (500 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/sensibio-gel-detergente-delicato-lenitivo-e-struccante/p-16026781/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129800843_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRSENW_KCLG01",
    skinTypes: ["sensibile", "normale", "secca"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-sebium-h2o",
    name: "Sébium H2O",
    brand: "Bioderma",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 14.45,
    description: "Acqua micellare per pelli grasse e miste (500 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/sebium-h2o-acqua-micellare-per-pelli-miste-e-grasse/p-75977/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129812013_01-o__31.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRSEBW_KECL20",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-hydrabio-gel-moussant",
    name: "Hydrabio Gel Moussant",
    brand: "Bioderma",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: false,
    price: 18.7,
    description: "Gel micellare detergente effetto idratante (400 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/hydrabio-gel-moussant-gel-micellare-detergente-effetto-idratante/p-16372402/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129814390_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIREPWQ_MYUM01",
    skinTypes: ["secca", "normale"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-svr-sensifine-latte-detergente",
    name: "Sensifine Latte Detergente",
    brand: "SVR",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 9.77,
    description: "Latte detergente lenitivo per pelli sensibili con tendenza all'arrossamento (200 ml)",
    affiliateUrl: "https://www.notino.it/svr/sensifine-latte-detergente-lenitivo-per-pelli-sensibili-con-tendenza-allarrossamento/p-627054/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/svr/3401360084070_01-o__12.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:SVRSENW_KFLT10",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-ducray-dexyane",
    name: "Dexyane",
    brand: "Ducray",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: false,
    price: 14.36,
    description: "Olio detergente per pelli molto secche, sensibili e atopiche (400 ml)",
    affiliateUrl: "https://www.notino.it/ducray/dexyane-olio-detergente-per-pelli-molto-secche/p-16082738/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770203028_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURDEXW_KBOI01",
    skinTypes: ["secca", "sensibile"],
    concerns: ["barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-isdin-acniben-mattifying-cleanser",
    name: "Acniben Mattifying Cleanser",
    brand: "ISDIN",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: false,
    price: 19.12,
    description: "Gel di pulizia profonda con acido salicilico (400 ml)",
    affiliateUrl: "https://www.notino.it/isdin/acniben-teen-skin-gel-di-pulizia-profonda-con-acido-salicilico/p-16241510/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/isdin/8429420227590_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:ISDACNW_KECL01",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "pori-dilatati"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-caudalie-vinoclean-olio-struccante",
    name: "Vinoclean Olio Struccante",
    brand: "Caudalie",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: false,
    price: 18.3,
    description: "Olio struccante detergente per viso e occhi (150 ml)",
    affiliateUrl: "https://www.notino.it/caudalie/vinoclean-olio-struccante-detergente-per-viso-e-occhi/p-16066621/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/caudalie/3522930003175_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CAUVNCW_KECL15",
    skinTypes: ["normale", "secca", "mista", "grassa"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cosrx-low-ph-good-morning-gel-cleanser",
    name: "Low pH Good Morning Gel Cleanser",
    brand: "COSRX",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: true,
    price: 11.47,
    description: "Gel detergente pH 5,0 - 6,0 (150 ml)",
    affiliateUrl: "https://www.notino.it/cosrx/good-morning-gel-detergente/p-15811164/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cosrx/8809416470511_01-o__3.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CSXGOMW_KFGL10",
    skinTypes: ["mista", "grassa", "normale"],
    concerns: ["acne-sebo", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cosrx-salicylic-acid-daily-gentle-cleans",
    name: "Salicylic Acid Daily Gentle Cleanser",
    brand: "COSRX",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: true,
    price: 10.62,
    description: "Schiuma detergente attiva (150 ml)",
    affiliateUrl: "https://www.notino.it/cosrx/cosrx-salicylic-acid-schiuma-detergente-attiva/p-15959986/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cosrx/8809416471112_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CSXSAAW_KFCR25",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "pori-dilatati"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-beauty-of-joseon-radiance-cleansing-balm",
    name: "Radiance Cleansing Balm",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: true,
    price: 13.51,
    description: "Balsamo struccante e detergente (100 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/radiance-cleansing-balm-balsamo-struccante-e-detergente/p-16116899/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809442263934_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJRCBW_KMUR01",
    skinTypes: ["secca", "normale", "mista"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-anua-heartleaf-pore-control-cleansing-oi",
    name: "Heartleaf Pore Control Cleansing Oil",
    brand: "Anua",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: true,
    price: 20.31,
    description: "Olio struccante detergente effetto idratante (200 ml)",
    affiliateUrl: "https://www.notino.it/anua/heartleaf-pore-control-cleansing-oil-olio-struccante-detergente-effetto-idratante/p-16241057/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/anua/8809640732829_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AUAHRTW_KMUR01",
    skinTypes: ["grassa", "mista", "sensibile"],
    concerns: ["pori-dilatati", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-skin1004-madagascar-centella-ampoule-foa",
    name: "Madagascar Centella Ampoule Foam",
    brand: "SKIN1004",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: true,
    price: 13.51,
    description: "Mousse detergente in crema per pelli sensibili (125 ml)",
    affiliateUrl: "https://www.notino.it/skin1004/madagascar-centella-ampoule-foam-mousse-detergente-in-crema-per-pelli-sensibili/p-16136316/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/skin1004/8809576261127_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:S04MDCW_KECL02",
    skinTypes: ["sensibile", "mista"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-torriden-balanceful-cleansing-gel",
    name: "Balanceful Cleansing Gel",
    brand: "Torriden",
    gender: "unisex",
    category: "detergenti",
    tier: "top",
    korean: true,
    price: 19.55,
    description: "Gel detergente delicato con effetto lenitivo (200 ml)",
    affiliateUrl: "https://www.notino.it/torriden/balanceful-cleansing-gel-gel-detergente-delicato-con-effetto-lenitivo/p-16394057/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/torriden/8809784600824_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:TRJBALW_KECL01",
    skinTypes: ["sensibile", "mista"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-dr-althea-amino-acid-gentle-bubble-clean",
    name: "Amino Acid Gentle Bubble Cleanser",
    brand: "Dr. Althea",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: true,
    price: 11.47,
    description: "Mousse detergente delicata con amminoacidi (140 ml)",
    affiliateUrl: "https://www.notino.it/dr-althea/amino-acid-gentle-bubble-cleanser-mousse-detergente-delicata-con-amminoacidi/p-16346177/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/dr_althea/8809447251400_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DTEBKRW_KMUP01",
    skinTypes: ["sensibile", "normale", "secca"],
    concerns: ["barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-medicube-zero-foam-cleanser",
    name: "Zero Foam Cleanser",
    brand: "Medicube",
    gender: "unisex",
    category: "detergenti",
    tier: "base",
    korean: true,
    price: 12.83,
    description: "Mousse detergente delicata con effetto lenitivo (120 ml)",
    affiliateUrl: "https://www.notino.it/medicube/zero-foam-cleanser-mousse-detergente-delicata-con-effetto-lenitivo/p-16315851/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/medicube/8800240575298_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:MCBZERW_KECL01",
    skinTypes: ["mista", "grassa", "sensibile"],
    concerns: ["pori-dilatati", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "mn-la-mer-the-essence-foaming-cleanser",
    name: "The Essence Foaming Cleanser",
    brand: "La Mer",
    gender: "unisex",
    category: "detergenti",
    tier: "premium",
    korean: false,
    price: 130,
    description: "Schiuma detergente delicata che rispetta l'idratazione della pelle.",
    affiliateUrl: "https://www.marionnaud.it/la-mer/the-essence-foaming-cleanser/schiuma-detergente/p/BP_345984?channable=092674756e697175655f696400333435393834b2&varSel=345984",
    linkPending: true,
    merchant: "Marionnaud",
    feedId: "cj:6585019:345984",
    skinTypes: ["normale", "secca", "mista"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "mn-sisley-gel-nettoyant-gommant",
    name: "Gel Nettoyant Gommant",
    brand: "Sisley",
    gender: "unisex",
    category: "detergenti",
    tier: "premium",
    korean: false,
    price: 130,
    description: "Gel detergente esfoliante delicato che affina la grana della pelle.",
    affiliateUrl: "https://www.marionnaud.it/sisley/viso/gel-nettoyant-gommant/p/BP_44137?channable=092674756e697175655f696400343431333707&varSel=44137",
    linkPending: true,
    merchant: "Marionnaud",
    feedId: "cj:6585019:44137",
    skinTypes: ["normale", "mista"],
    concerns: ["pori-dilatati"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-cerave-hydrating-hyaluronic-acid-serum",
    name: "Hydrating Hyaluronic Acid Serum",
    brand: "CeraVe",
    gender: "unisex",
    category: "sieri",
    tier: "base",
    korean: false,
    price: 15.89,
    description: "Siero ialuronico (30 ml)",
    affiliateUrl: "https://www.notino.it/cerave/hydrating-hyaluronic-acid-serum-siero-ialuronico/p-16229318/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cerave/3606000560833_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CEVHDRW_KFSR74",
    skinTypes: ["secca", "normale", "mista"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cerave-resurfacing-retinol-serum",
    name: "Resurfacing Retinol Serum",
    brand: "CeraVe",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 20.9,
    description: "Siero rigenerante con retinolo (30 ml)",
    affiliateUrl: "https://www.notino.it/cerave/blemish-control-siero-attivo-con-retinolo/p-16142856/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cerave/3337875829007_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CEVFERW_KCLG03",
    skinTypes: ["mista", "grassa", "normale"],
    concerns: ["anti-age", "acne-sebo"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-la-roche-posay-hyalu-b5-suractivated-ser",
    name: "Hyalu B5 Suractivated Serum",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 37.74,
    description: "Siero concentrato antirughe (30 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/hyalu-b5-suractivated-serum-siero-concentrato-antirughe/p-16328156/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875920582_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPSDCU_ZJQE06",
    skinTypes: ["secca", "normale", "sensibile"],
    concerns: ["anti-age", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-la-roche-posay-effaclar-siero-concentrat",
    name: "Effaclar Siero Concentrato",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 31.9,
    description: "Siero concentrato per pelli problematiche, acne (30 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/effaclar-siero-concentrato-per-pelli-problematiche-acne/p-16065669/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875722827_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPEFCW_KFSR01",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "pori-dilatati"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-la-roche-posay-pure-vitamin-c12",
    name: "Pure Vitamin C12",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 35,
    description: "Siero illuminante con vitamina C antirughe (30 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/pure-vitamin-c12-siero-illuminante-con-vitamina-c-antirughe/p-16269149/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875909235_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPOQYW_KFSR01",
    skinTypes: ["normale", "mista"],
    concerns: ["macchie-luminosita", "anti-age"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-la-roche-posay-cicaplast-b5-siero",
    name: "Cicaplast B5 Siero",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 31.62,
    description: "Siero rigenerante per uso quotidiano (30 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/cicaplast-b5-siero-rigenerante-per-uso-quotidiano/p-16203220/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875837804_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPCB5W_KSER96",
    skinTypes: ["sensibile", "secca"],
    concerns: ["barriera-cutanea", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-hydrance-boost",
    name: "Hydrance Boost",
    brand: "Avène",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 25.5,
    description: "Siero concentrato per un'idratazione intensa della pelle (30 ml)",
    affiliateUrl: "https://www.notino.it/avene/hydrance-boost-siero-concentrato-per-unidratazione-intensa-della-pelle/p-16185637/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770388954_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVECOUM_KASB10",
    skinTypes: ["secca", "sensibile", "normale"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-sensibio-ar-bl-serum",
    name: "Sensibio AR+ Bl-sérum",
    brand: "Bioderma",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 26.86,
    description: "Siero lenitivo contro gli arrossamenti (30 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/sensibio-ar-bl-serum-siero-lenitivo-contro-gli-arrossamenti/p-16283030/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129812518_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRSARW_KMUR01",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-mineral-89-booster",
    name: "Minéral 89 Booster",
    brand: "Vichy",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 28.47,
    description: "Booster rinforzante e rimpolpante con acido ialuronico (75 ml)",
    affiliateUrl: "https://www.notino.it/vichy/mineral-89-booster-rinforzante-e-rimpolpante-con-acido-ialuronico/p-15952765/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875609418_01-o__3.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHMINW_KFSR15",
    skinTypes: ["secca", "grassa", "mista", "normale", "sensibile"],
    concerns: ["idratazione", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-liftactiv-collagen-specialist-16",
    name: "Liftactiv Collagen Specialist 16",
    brand: "Vichy",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 42.92,
    description: "Siero rinforzante con collagene (30 ml)",
    affiliateUrl: "https://www.notino.it/vichy/liftactiv-collagen-specialist-16-siero-rinforzante-con-collagene/p-16284868/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875912600_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHLNGW_KFCR01",
    skinTypes: ["normale", "secca", "mista"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-liftactiv-retinol-specialist-serum",
    name: "Liftactiv Retinol Specialist Serum",
    brand: "Vichy",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 41.05,
    description: "Trattamento intensivo antirughe con retinolo (30 ml)",
    affiliateUrl: "https://www.notino.it/vichy/liftactiv-retinol-specialist-serum-trattamento-intensivo-antirughe-con-retinolo/p-16164563/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875821636_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHKPBW_KFEM01",
    skinTypes: ["normale", "mista", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-svr-ampoule-c-anti-ox",
    name: "Ampoule [C] Anti-ox",
    brand: "SVR",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 24.22,
    description: "Siero antiossidante con vitamina C (30 ml)",
    affiliateUrl: "https://www.notino.it/svr/ampoule-anti-ox-siero-antiossidante-con-vitamina-c/p-16249841/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/svr/3662361000401_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:SVRAMPW_KFSR04",
    skinTypes: ["normale", "mista"],
    concerns: ["macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-caudalie-resveratrol-lift-siero",
    name: "Resveratrol-Lift Siero",
    brand: "Caudalie",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: false,
    price: 45.9,
    description: "Siero rassodante intenso antirughe (30 ml)",
    affiliateUrl: "https://www.notino.it/caudalie/resveratrol-lift-siero-rassodante-intenso-antirughe/p-16273265/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/caudalie/3522930004516_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CAUOLKW_KFSR01",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cosrx-the-alpha-arbutin-2-discoloration-",
    name: "The Alpha-Arbutin 2 Discoloration Care",
    brand: "COSRX",
    gender: "unisex",
    category: "sieri",
    tier: "base",
    korean: true,
    price: 14.36,
    description: "Siero per pelli iperpigmentate (50 ml)",
    affiliateUrl: "https://www.notino.it/cosrx/the-alpha-arbutin-2-discoloration-care-siero-per-pelli-iperpigmentate/p-16342653/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cosrx/8809598454880_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CSXTAAW_KFSR01",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cosrx-retinol-0-5",
    name: "Retinol 0.5",
    brand: "COSRX",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 22.95,
    description: "Siero all'olio antirughe (20 ml)",
    affiliateUrl: "https://www.notino.it/cosrx/retinol-05-siero-allolio-antirughe/p-16172299/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cosrx/8809598454965_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CSXRTNW_KFCO01",
    skinTypes: ["normale", "mista"],
    concerns: ["anti-age"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-beauty-of-joseon-glow-deep-serum-rice-ar",
    name: "Glow Deep Serum Rice + Arbutin",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "sieri",
    tier: "base",
    korean: true,
    price: 12,
    description: "Siero illuminante per unificare il tono della pelle (30 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/glow-deep-serum-rice-arbutin-siero-illuminante-per-unificare-il-tono-della-pelle/p-16116937/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809738312728_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJGDSW_KFSR01",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-beauty-of-joseon-calming-barrier-serum",
    name: "Calming Barrier Serum",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "sieri",
    tier: "base",
    korean: true,
    price: 10.11,
    description: "Siero per lenire e rinforzare le pelli sensibili (30 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/calming-barrier-serum-siero-per-lenire-e-rinforzare-le-pelli-sensibili/p-16398587/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809968133100_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJMGFX_DLYV06",
    skinTypes: ["sensibile", "secca"],
    concerns: ["barriera-cutanea", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-beauty-of-joseon-light-on-serum-centella",
    name: "Light On Serum Centella + Vita C",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "sieri",
    tier: "base",
    korean: true,
    price: 13.17,
    description: "Siero illuminante con effetto lenitivo (30 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/light-on-serum-centella-vita-c-siero-illuminante-con-effetto-lenitivo/p-16223370/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809875906477_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJLOSW_KFSR01",
    skinTypes: ["normale", "mista", "sensibile"],
    concerns: ["macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-anua-peach-70-niacin-serum",
    name: "Peach 70% Niacin Serum",
    brand: "Anua",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 24.56,
    description: "Siero idratante illuminante per pori dilatati e rughe (30 ml)",
    affiliateUrl: "https://www.notino.it/anua/peach-70-niacin-serum-siero-idratante-illuminante-per-pori-dilatati-e-rughe/p-16246260/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/anua/8809640733550_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AUAPEAW_KFSR02",
    skinTypes: ["mista", "grassa", "normale"],
    concerns: ["pori-dilatati", "macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-anua-pdrn-hyaluronic-acid-capsule-100-se",
    name: "PDRN Hyaluronic Acid Capsule 100 Serum",
    brand: "Anua",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 24.9,
    description: "Siero idratante e nutriente con collagene (30 ml)",
    affiliateUrl: "https://www.notino.it/anua/pdrn-hyaluronic-acid-capsule-100-serum-siero-idratante-e-nutriente-con-collagene/p-16313399/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/anua/8809640736667_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AUAOHXW_KFSR01",
    skinTypes: ["secca", "normale"],
    concerns: ["idratazione", "anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-anua-bha-2-gentle-exfoliating-toner",
    name: "BHA 2% Gentle Exfoliating Toner",
    brand: "Anua",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 26.35,
    description: "Lozione tonica esfoliante delicata per pelli problematiche, acne (150 ml)",
    affiliateUrl: "https://www.notino.it/anua/bha-2-gentle-exfoliating-toner-lozione-tonica-esfoliante-delicata-per-pelli-problematiche-acne/p-16268709/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/anua/8809640734519_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AUABHAW_KTON01",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "pori-dilatati"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-skin1004-madagascar-centella-hyalu-cica-",
    name: "Madagascar Centella Hyalu-Cica First Ampoule",
    brand: "SKIN1004",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 22.01,
    description: "Siero idratante rivitalizzante (100 ml)",
    affiliateUrl: "https://www.notino.it/skin1004/madagascar-centella-hyalu-cica-first-ampoule-siero-idratante-rivitalizzante/p-16153566/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/skin1004/8809576261486_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:S04MCHW_KFSR04",
    skinTypes: ["sensibile", "secca", "normale"],
    concerns: ["idratazione", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-skin1004-madagascar-centella-tea-trica-r",
    name: "Madagascar Centella Tea-Trica Relief Ampoule",
    brand: "SKIN1004",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 21.16,
    description: "Siero lenitivo viso per pelli problematiche, acne (100 ml)",
    affiliateUrl: "https://www.notino.it/skin1004/madagascar-centella-tea-trica-relief-ampoule-siero-lenitivo-viso-per-pelli-problematiche-acne/p-16153553/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/skin1004/8809576261677_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:S04MTTW_KFSR01",
    skinTypes: ["grassa", "mista", "sensibile"],
    concerns: ["acne-sebo", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-round-lab-1025-dokdo-ampoule",
    name: "1025 Dokdo Ampoule",
    brand: "Round Lab",
    gender: "unisex",
    category: "sieri",
    tier: "base",
    korean: true,
    price: 11.47,
    description: "Siero viso idratante intenso con effetto lenitivo (45 g)",
    affiliateUrl: "https://www.notino.it/round-lab/1025-dokdo-ampoule-siero-viso-idratante-intenso-con-effetto-lenitivo/p-16359645/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/round_lab/8809657115479_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:ROLDKDW_KSER01",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-torriden-cellmazing-brightening-ampoule",
    name: "Cellmazing Brightening Ampoule",
    brand: "Torriden",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 23.8,
    description: "Siero illuminante per unificare il tono della pelle (30 ml)",
    affiliateUrl: "https://www.notino.it/torriden/cellmazing-brightening-ampoule-siero-illuminante-per-unificare-il-tono-della-pelle/p-16394079/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/torriden/8809784602002_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:TRJVJCB_JSOZ04",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-dr-althea-345-relief-serum",
    name: "345 Relief Serum",
    brand: "Dr. Althea",
    gender: "unisex",
    category: "sieri",
    tier: "base",
    korean: true,
    price: 14.87,
    description: "Siero idratante viso per rafforzare la barriera cutanea (30 ml)",
    affiliateUrl: "https://www.notino.it/dr-althea/345-relief-serum-siero-idratante-viso-per-rafforzare-la-barriera-cutanea/p-16398512/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/dr_althea/8809447257051_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DTECXNF_FWIK01",
    skinTypes: ["sensibile"],
    concerns: ["barriera-cutanea", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-medicube-pdrn-pink-peptide-serum",
    name: "PDRN Pink Peptide Serum",
    brand: "Medicube",
    gender: "unisex",
    category: "sieri",
    tier: "top",
    korean: true,
    price: 21.16,
    description: "Siero rassodante viso con peptidi (30 ml)",
    affiliateUrl: "https://www.notino.it/medicube/pdrn-pink-peptide-serum-siero-rassodante-viso-con-peptidi/p-16329864/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/medicube/8800256112470_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:MCBPDRW_KSER01",
    skinTypes: ["normale", "secca", "mista"],
    concerns: ["anti-age", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-filorga-ncef-revitalize-serum",
    name: "NCEF-Revitalize Serum",
    brand: "Filorga",
    gender: "unisex",
    category: "sieri",
    tier: "premium",
    korean: false,
    price: 64.5,
    description: "Siero rivitalizzante (30 ml)",
    affiliateUrl: "https://www.notino.it/filorga/ncef-revitalize-serum-siero-rivitalizzante/p-16263322/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/filorga/3540550015378_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:FILNCEW_KFSR01",
    skinTypes: ["normale", "secca", "mista"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "mn-sisley-hydra-global-siero",
    name: "Hydra-Global Siero",
    brand: "Sisley",
    gender: "unisex",
    category: "sieri",
    tier: "premium",
    korean: false,
    price: 269,
    description: "Siero idratante anti-età per pelli secche e disidratate.",
    affiliateUrl: "https://www.marionnaud.it/sisley/hydra-global/siero-viso/p/BP_125506?channable=092674756e697175655f6964003132353530365f&varSel=125506",
    linkPending: true,
    merchant: "Marionnaud",
    feedId: "cj:6585019:125506",
    skinTypes: ["secca", "normale"],
    concerns: ["idratazione", "anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "mn-la-mer-the-lifting-firming-serum",
    name: "The Lifting Firming Serum",
    brand: "La Mer",
    gender: "unisex",
    category: "sieri",
    tier: "premium",
    korean: false,
    price: 420,
    description: "Siero liftante e rassodante per contrastare la perdita di tono.",
    affiliateUrl: "https://www.marionnaud.it/la-mer/the-lifting-firming-serum/siero-viso/p/BP_313686?channable=092674756e697175655f69640033313336383663&varSel=313686",
    linkPending: true,
    merchant: "Marionnaud",
    feedId: "cj:6585019:313686",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cerave-oil-control-moisturising-gel-crea",
    name: "Oil Control Moisturising Gel-Cream",
    brand: "CeraVe",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 15.47,
    description: "Crema-gel idratante per pelli miste (52 ml)",
    affiliateUrl: "https://www.notino.it/cerave/oil-control-moisturising-gel-cream-crema-gel-idratante-per-pelli-miste/p-16271874/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cerave/3337875904513_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CEVHCSW_KCLG01",
    skinTypes: ["mista", "grassa"],
    concerns: ["acne-sebo", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cerave-skin-renewing-peptide-cream",
    name: "Skin Renewing Peptide Cream",
    brand: "CeraVe",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 28,
    description: "Crema notte rigenerante per la densità della pelle (48 g)",
    affiliateUrl: "https://www.notino.it/cerave/skin-renewing-peptide-night-cream-crema-notte-rigenerante-per-la-densita-della-pelle/p-16332877/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cerave/3337875903509_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CEVZJVU_ZCWY03",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-la-roche-posay-effaclar-supramolecular-c",
    name: "Effaclar Supramolecular Crema-Gel",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 15.72,
    description: "Crema-gel opacizzante contro la pelle lucida e i pori dilatati (40 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/effaclar-supramolecular-crema-gel-opacizzante-contro-la-pelle-lucida-e-i-pori-dilatati/p-16385460/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875950336_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPDKPB_CACV01",
    skinTypes: ["grassa", "mista"],
    concerns: ["pori-dilatati", "acne-sebo"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-la-roche-posay-toleriane-dermallergo",
    name: "Toleriane Dermallergo",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 26,
    description: "Crema idratante per pelli sensibili (40 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/toleriane-dermallergo-crema-idratante-per-pelli-sensibili/p-16095544/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875757614_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPDERW_KFCR02",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-la-roche-posay-hyalu-b5-crema",
    name: "Hyalu B5 Crema",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 29.9,
    description: "Crema idratante intensa con acido ialuronico (40 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/hyalu-b5-crema-idratante-intensa-con-acido-ialuronico/p-11604748/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875583589_01-o__5.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPHB5W_KFCR10",
    skinTypes: ["secca", "normale"],
    concerns: ["anti-age", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-la-roche-posay-nutritic",
    name: "Nutritic",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 22.95,
    description: "Crema nutriente per pelli secche e molto secche (50 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/nutritic-crema-nutriente-per-pelli-secche-e-molto-secche/p-93838/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337872413629_01__25.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPNUTW_KFCR10",
    skinTypes: ["secca"],
    concerns: ["barriera-cutanea", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-tolerance-control",
    name: "Tolérance Control",
    brand: "Avène",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 20.31,
    description: "Crema rigenerante per lenire la pelle (40 ml)",
    affiliateUrl: "https://www.notino.it/avene/tolerance-control-crema-rigenerante-per-lenire-la-pelle/p-16076001/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770138801_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVETOCW_KDCR01",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-hydrance-light-hydrating-emulsion",
    name: "Hydrance Light Hydrating Emulsion",
    brand: "Avène",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 17.25,
    description: "Emulsione idratante leggera (40 ml)",
    affiliateUrl: "https://www.notino.it/avene/avene-hydrance-emulsione-idratante-leggera/p-15963884/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770208962_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVEHYDW_KDCR06",
    skinTypes: ["normale", "mista"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-cleanance-hydra-soothing-cream",
    name: "Cleanance Hydra Soothing Cream",
    brand: "Avène",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 14.96,
    description: "Crema lenitiva effetto idratante (40 ml)",
    affiliateUrl: "https://www.notino.it/avene/cleanance-hydra-crema-lenitiva-effetto-idratante/p-447669/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770100891_01-o__24.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVECLHW_KFCR10",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-dermabsolu-redensifying-day-cream",
    name: "DermAbsolu Redensifying Day Cream",
    brand: "Avène",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 42.67,
    description: "Crema giorno rimodellante antirughe (50 ml)",
    affiliateUrl: "https://www.notino.it/avene/dermabsolu-redensifying-day-cream-crema-giorno-rimodellante-antirughe/p-16274725/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770395976_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVEVEMW_KDCR01",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-sensibio-ar",
    name: "Sensibio AR+",
    brand: "Bioderma",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 19.29,
    description: "Crema lenitiva per pelli sensibili con tendenza all'arrossamento (40 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/sensibio-ar-crema-lenitiva-per-pelli-sensibili-con-tendenza-allarrossamento/p-16283031/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129812099_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRSARW_KMUR02",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-atoderm-nutritive",
    name: "Atoderm Nutritive",
    brand: "Bioderma",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 9.26,
    description: "Crema giorno per pelli secche e sensibili (40 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/atoderm-nutritive-crema-nutriente-per-pelli-secche-e-molto-secche/p-15735420/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3401399373008_01__2.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRATNW_KFCL20",
    skinTypes: ["secca", "sensibile"],
    concerns: ["barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-hydrabio-light",
    name: "Hydrabio Light",
    brand: "Bioderma",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 18.61,
    description: "Crema idratante leggera per pelli normali e miste (40 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/hydrabio-light-crema-idratante-leggera-per-pelli-normali-e-miste/p-16377914/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129814307_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRFFFN_MYUM04",
    skinTypes: ["normale", "mista"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-mineral-89-crema-72h",
    name: "Minéral 89 Crema 72h",
    brand: "Vichy",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 20,
    description: "Crema idratante viso 72 ore (50 ml)",
    affiliateUrl: "https://www.notino.it/vichy/mineral-89-crema-idratante-viso-72-ore/p-16177676/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875831888_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHDNHW_KECR01",
    skinTypes: ["secca", "grassa", "mista", "normale", "sensibile"],
    concerns: ["idratazione", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-neovadiol-magistral-crema-giorno",
    name: "Neovadiol Magistral Crema Giorno",
    brand: "Vichy",
    gender: "donna",
    category: "creme",
    tier: "top",
    korean: false,
    price: 40.5,
    description: "Crema rassodante e nutriente giorno (50 ml)",
    affiliateUrl: "https://www.notino.it/vichy/neovadiol-after-menopause-crema-rassodante-e-nutriente-giorno/p-16091140/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875774031_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHNEOW_KDCR14",
    skinTypes: ["secca", "normale"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-liftactiv-collagen-specialist-16-d",
    name: "Liftactiv Collagen Specialist 16 Day",
    brand: "Vichy",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 33.74,
    description: "Crema rigenerante liftante antirughe (50 ml)",
    affiliateUrl: "https://www.notino.it/vichy/liftactiv-collagen-specialist-crema-rigenerante-liftante-antirughe/p-15796386/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875607254_01-o__3.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHLCSW_KFCR10",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-liftactiv-pigment-specialist-b3",
    name: "Liftactiv Pigment Specialist B3",
    brand: "Vichy",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 38.25,
    description: "Crema notte con retinolo (50 ml)",
    affiliateUrl: "https://www.notino.it/vichy/liftactiv-collagen-specialist-crema-notte-con-retinolo/p-16249685/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875873086_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHLBRW_KNCR14",
    skinTypes: ["normale", "mista"],
    concerns: ["macchie-luminosita", "anti-age"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-svr-sensifine-ar",
    name: "Sensifine AR",
    brand: "SVR",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 16.06,
    description: "Crema colorata neutralizzante contro il rossore (40 ml)",
    affiliateUrl: "https://www.notino.it/svr/sensifine-ar-crema-colorata-neutralizzante-contro-il-rossore/p-16241511/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/svr/3662361001859_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:SVRSNAW_KFCR19",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-svr-sebiaclear-hydra",
    name: "Sebiaclear Hydra",
    brand: "SVR",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 10.71,
    description: "Crema lenitiva e idratante per pelli con imperfezioni (40 ml)",
    affiliateUrl: "https://www.notino.it/svr/sebiaclear-hydra-crema-lenitiva-e-idratante-per-pelli-con-imperfezioni/p-15762961/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/svr/3662361003594_01-o__4.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:SVRSEHW_KFCR10",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-svr-biotic-c20",
    name: "Biotic [C20]",
    brand: "SVR",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 31.02,
    description: "Crema rivitalizzante e illuminante (50 ml)",
    affiliateUrl: "https://www.notino.it/svr/biotic-c20-crema-rivitalizzante-e-illuminante/p-16391553/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/svr/3662361004294_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:SVRBTOA_HVGY04",
    skinTypes: ["normale", "mista"],
    concerns: ["macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: false,
  },
  {
    id: "nt-svr-densitium-creme",
    name: "Densitium Creme",
    brand: "SVR",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 27.11,
    description: "Crema viso per ringiovanire la pelle (50 ml)",
    affiliateUrl: "https://www.notino.it/svr/densitium-crema-viso-per-ringiovanire-la-pelle/p-16102256/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/svr/3662361001941_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:SVRDENW_KFCR11",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-ducray-keracnyl-repair-soothing-compensa",
    name: "Keracnyl Repair Soothing Compensating Cream",
    brand: "Ducray",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 14.87,
    description: "Crema lenitiva e idratante per pelli sensibili con tendenza all'acne (50 ml)",
    affiliateUrl: "https://www.notino.it/ducray/keracnyl-repair-soothing-compensating-cream-crema-lenitiva-e-idratante-per-pelli-sensibili-con-tendenza-allacne/p-16317126/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770391251_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURRPSW_KSHA05",
    skinTypes: ["grassa", "mista", "sensibile"],
    concerns: ["acne-sebo", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-ducray-kelual-ds-soothing-cream",
    name: "Kelual DS Soothing Cream",
    brand: "Ducray",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 12.41,
    description: "Crema lenitiva per pelli secche e irritate (40 ml)",
    affiliateUrl: "https://www.notino.it/ducray/kelual-ds-crema-lenitiva-per-cuoi-capelluti-irritati/p-16264313/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770392371_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURNLTW_KFCR01",
    skinTypes: ["mista", "grassa", "sensibile"],
    concerns: ["rossori-sensibilita", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-caudalie-vinohydra-gel-moisturizer",
    name: "VinoHydra Gel Moisturizer",
    brand: "Caudalie",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 19.1,
    description: "Gel idratante per pelli miste (60 ml)",
    affiliateUrl: "https://www.notino.it/caudalie/vinohydra-gel-moisturizer-gel-idratante-per-pelli-miste/p-16244741/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/caudalie/3522930004394_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CAUDHOW_KFCR11",
    skinTypes: ["mista", "grassa"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-caudalie-resveratrol-lift-lightweight-fi",
    name: "Resveratrol-Lift Lightweight Firming Cashmere Cream",
    brand: "Caudalie",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 37.9,
    description: "Crema lifting leggera per rassodare la pelle (40 ml)",
    affiliateUrl: "https://www.notino.it/caudalie/resveratrol-lift-lightweight-firming-cashmere-cream-crema-lifting-leggera-per-rassodare-la-pelle/p-16273255/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/caudalie/3522930004523_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CAUAOEW_KDCR01",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cosrx-hydrium-moisture-power",
    name: "Hydrium Moisture Power",
    brand: "COSRX",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 20.31,
    description: "Crema idratante alle ceramidi (50 ml)",
    affiliateUrl: "https://www.notino.it/cosrx/hydrium-moisture-power-crema-idratante-alle-ceramidi/p-16112692/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cosrx/8809598453623_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CSXHYDW_KFCR01",
    skinTypes: ["secca", "normale"],
    concerns: ["idratazione", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cosrx-ac-collection",
    name: "AC Collection",
    brand: "COSRX",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 22.86,
    description: "Crema idratante e lenitiva per pelli problematiche (80 ml)",
    affiliateUrl: "https://www.notino.it/cosrx/clear-fit-master-patch-crema-idratante-e-lenitiva-per-pelli-problematiche/p-16172022/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cosrx/8809598453586_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CSXACCW_KFCR05",
    skinTypes: ["grassa", "mista"],
    concerns: ["acne-sebo"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-beauty-of-joseon-dynasty-cream",
    name: "Dynasty Cream",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 21.67,
    description: "Crema idratante intensa illuminante (100 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/dynasty-cream-crema-idratante-intensa-illuminante/p-16339739/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809954941498_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJDYNW_KFCR02",
    skinTypes: ["secca", "normale"],
    concerns: ["idratazione", "macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-beauty-of-joseon-red-bean-water-gel",
    name: "Red Bean Water Gel",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: true,
    price: 13.51,
    description: "Gel idratante intenso per pelli grasse (100 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/red-bean-water-gel-gel-idratante-intenso-per-pelli-grasse/p-16185809/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809738316993_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJREBW_KFCR01",
    skinTypes: ["grassa", "mista"],
    concerns: ["idratazione", "pori-dilatati"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-beauty-of-joseon-revive-firming-moisturi",
    name: "Revive Firming Moisturizer Ginseng + Retinol",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 17.85,
    description: "Crema nutriente lisciante effetto idratante (60 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/revive-firming-moisturizer-ginsegn-retinol-crema-nutriente-lisciante-effetto-idratante/p-16373007/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809968133179_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJKYWG_AUWO05",
    skinTypes: ["normale", "mista"],
    concerns: ["anti-age"],
    pregnancySafe: false,
    sensitiveSafe: false,
  },
  {
    id: "nt-anua-pdrn-100-hyaluronic-acid-moisturizi",
    name: "PDRN 100 Hyaluronic Acid Moisturizing Cream",
    brand: "Anua",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 17.34,
    description: "Crema di idratazione profonda con collagene (60 ml)",
    affiliateUrl: "https://www.notino.it/anua/pdrn-100-hyaluronic-acid-moisturizing-cream-crema-di-idratazione-profonda-con-collagene/p-16382086/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/anua/8800307371252_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AUAUPCZ_AUWO02",
    skinTypes: ["secca", "normale"],
    concerns: ["idratazione", "anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-anua-heartleaf-centella-red-spot-cream",
    name: "Heartleaf Centella Red Spot Cream",
    brand: "Anua",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: true,
    price: 10.11,
    description: "Crema idratante leggera con effetto lenitivo (30 g)",
    affiliateUrl: "https://www.notino.it/anua/heartleaf-centella-red-spot-cream-crema-idratante-leggera-con-effetto-lenitivo/p-16382409/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/anua/8800307371283_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AUARJIX_AUWO03",
    skinTypes: ["sensibile", "grassa"],
    concerns: ["rossori-sensibilita", "acne-sebo"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-skin1004-madagascar-centella-cream",
    name: "Madagascar Centella Cream",
    brand: "SKIN1004",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 19.5,
    description: "Crema lenitiva viso per pelli sensibili e irritate (75 ml)",
    affiliateUrl: "https://www.notino.it/skin1004/madagascar-centella-cream-crema-lenitiva-viso-per-pelli-sensibili-e-irritate/p-16136259/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/skin1004/8809576260441_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:S04MDCW_KFCR01",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-round-lab-1025-dokdo-cream",
    name: "1025 Dokdo Cream",
    brand: "Round Lab",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 20.82,
    description: "Crema rigenerante e idratante per pelli secche e sensibili (80 ml)",
    affiliateUrl: "https://www.notino.it/round-lab/1025-dokdo-cream-crema-rigenerante-e-idratante-per-pelli-secche-e-sensibili/p-16246283/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/round_lab/8809738600245_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:ROLDKDW_KFCR02",
    skinTypes: ["secca", "sensibile"],
    concerns: ["idratazione", "barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-torriden-solid-in-cream",
    name: "Solid In Cream",
    brand: "Torriden",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 26.35,
    description: "Crema idratante viso per rafforzare la barriera cutanea (70 ml)",
    affiliateUrl: "https://www.notino.it/torriden/solid-in-cream-crema-idratante-viso-per-rafforzare-la-barriera-cutanea/p-16394077/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/torriden/8809784602958_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:TRJPMMO_JSOZ07",
    skinTypes: ["secca", "sensibile"],
    concerns: ["barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-dr-althea-147-barrier-cream",
    name: "147 Barrier Cream",
    brand: "Dr. Althea",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 18.27,
    description: "Crema nutriente per rafforzare la barriera cutanea (50 ml)",
    affiliateUrl: "https://www.notino.it/dr-althea/147-barrier-cream-crema-nutriente-per-rafforzare-la-barriera-cutanea/p-16315836/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/dr_althea/8809447251363_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DTE147W_KFCR01",
    skinTypes: ["secca", "sensibile"],
    concerns: ["barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-medicube-txa-niacinamide-capsule-cream",
    name: "TXA Niacinamide Capsule Cream",
    brand: "Medicube",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 22.52,
    description: "Crema illuminante contro le macchie scure (55 ml)",
    affiliateUrl: "https://www.notino.it/medicube/txa-niacinamide-capsule-cream-crema-illuminante-contro-le-occhiaie/p-16363878/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/medicube/8800289461088_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:MCBTXAW_KFCR01",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-medicube-exosome-cica-cream",
    name: "Exosome CICA Cream",
    brand: "Medicube",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 20.82,
    description: "Crema idratante viso con effetto lenitivo (50 ml)",
    affiliateUrl: "https://www.notino.it/medicube/exosome-cica-cream-crema-idratante-viso-con-effetto-lenitivo/p-16359261/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/medicube/8800289478239_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:MCBECIW_KFCR01",
    skinTypes: ["sensibile"],
    concerns: ["rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-filorga-hyalu-filler",
    name: "Hyalu-Filler",
    brand: "Filorga",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 40.5,
    description: "Crema riempitiva effetto ringiovanente (50 ml)",
    affiliateUrl: "https://www.notino.it/filorga/hyalu-filler-crema-riempitiva-effetto-ringiovanente/p-16316215/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/filorga/3540550017525_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:FILHYAW_KFCR01",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-filorga-neocica",
    name: "Neocica",
    brand: "Filorga",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 25.07,
    description: "Crema idratante trattante per pelli irritate (40 ml)",
    affiliateUrl: "https://www.notino.it/filorga/medi-cosmetique-neocica-trattamento-localizzato-per-pelli-irritate/p-495972/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/filorga/3401353695146_01-o__18.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:FILMCRW_KBOC10",
    skinTypes: ["sensibile"],
    concerns: ["barriera-cutanea"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "mn-sisley-hydra-flash",
    name: "Hydra-Flash",
    brand: "Sisley",
    gender: "unisex",
    category: "creme",
    tier: "premium",
    korean: false,
    price: 214,
    description: "Crema-gel idratante intensa per pelli disidratate.",
    affiliateUrl: "https://www.marionnaud.it/sisley/viso/hydra-flash/p/BP_44168?channable=092674756e697175655f69640034343136388a&varSel=44168",
    linkPending: true,
    merchant: "Marionnaud",
    feedId: "cj:6585019:44168",
    skinTypes: ["secca", "normale"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "mn-sisley-creme-reparatrice",
    name: "Crème Réparatrice",
    brand: "Sisley",
    gender: "unisex",
    category: "creme",
    tier: "premium",
    korean: false,
    price: 192,
    description: "Crema riparatrice lenitiva per pelli sensibili e fragilizzate.",
    affiliateUrl: "https://www.marionnaud.it/sisley/creme/creme-reparatrice-50-ml/p/BP_44180?channable=092674756e697175655f696400343431383083&varSel=44180",
    linkPending: true,
    merchant: "Marionnaud",
    feedId: "cj:6585019:44180",
    skinTypes: ["sensibile", "secca"],
    concerns: ["barriera-cutanea", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "mn-la-mer-the-fresh-creme",
    name: "The Fresh Crème",
    brand: "La Mer",
    gender: "unisex",
    category: "creme",
    tier: "premium",
    korean: false,
    price: 115,
    description: "Crema rinfrescante e rigenerante dalla texture leggera.",
    affiliateUrl: "https://www.marionnaud.it/la-mer/the-fresh-creme/crema-rinfrescante-rigenerante-intensa/p/BP_359396?channable=092674756e697175655f69640034333338383328&varSel=433883",
    linkPending: true,
    merchant: "Marionnaud",
    feedId: "cj:6585019:433883",
    skinTypes: ["normale", "mista"],
    concerns: ["idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-men-crema-idratante-anti-age",
    name: "Men Crema Idratante Anti-Age",
    brand: "Avène",
    gender: "uomo",
    category: "creme",
    tier: "top",
    korean: false,
    price: 23.54,
    description: "Crema idratante anti-age per pelli sensibili (50 ml)",
    affiliateUrl: "https://www.notino.it/avene/men-crema-idratante-anti-age-per-pelli-sensibili/p-495313/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770038545_01-o__20.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVEMENM_KFCR20",
    skinTypes: ["normale", "secca", "sensibile"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-homme-structure-force",
    name: "Homme Structure Force",
    brand: "Vichy",
    gender: "uomo",
    category: "creme",
    tier: "top",
    korean: false,
    price: 27.03,
    description: "Crema rassodante antirughe con acido ialuronico (50 ml)",
    affiliateUrl: "https://www.notino.it/vichy/homme-structure-force-crema-rassodante-antirughe-con-acido-ialuronico/p-15945361/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875647212_01.-o__3.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHHSFM_KFCR10",
    skinTypes: ["normale", "secca"],
    concerns: ["anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cerave-invisible-hydrating-fluid-sunscre",
    name: "Invisible Hydrating Fluid Sunscreen SPF 50",
    brand: "CeraVe",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 16.57,
    description: "Lozione protettiva effetto idratante SPF 50 (50 ml)",
    affiliateUrl: "https://www.notino.it/cerave/invisible-hydrating-fluid-sunscreen-spf-50-lozione-protettiva-effetto-idratante/p-16366566/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cerave/3337875945660_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CEVFGNU_DJCE05",
    skinTypes: ["secca", "normale"],
    concerns: ["protezione-solare", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-la-roche-posay-anthelios-xl",
    name: "Anthelios XL",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 11.9,
    description: "Crema-gel opacizzante SPF 50+ (50 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/anthelios-xl-crema-gel-opacizzante-spf50/p-15713075/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875546409_01-o__4.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPAXLW_KPCR42",
    skinTypes: ["grassa", "mista"],
    concerns: ["protezione-solare", "acne-sebo"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-la-roche-posay-anthelios-age-correct-cc",
    name: "Anthelios Age Correct CC",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 30.9,
    description: "Cream antirughe SPF 50 (50 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/anthelios-age-correct-cc-cream-antirughe-spf-50/p-16075494/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875764353_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPAGCW_KFCR04",
    skinTypes: ["normale", "secca"],
    concerns: ["protezione-solare", "anti-age", "macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-sun-ultra-serum-activates-glow",
    name: "Sun Ultra Serum Activates Glow",
    brand: "Avène",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 34,
    description: "Siero protettivo illuminante SPF 50+ (30 ml)",
    affiliateUrl: "https://www.notino.it/avene/sun-ultra-serum-activates-glow-siero-protettivo-illuminante/p-16374691/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282771000572_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVESUNW_KFCR03",
    skinTypes: ["normale", "secca"],
    concerns: ["protezione-solare", "macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-avene-sun-fragrance-free-cream",
    name: "Sun Fragrance-Free Cream",
    brand: "Avène",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 17.5,
    description: "Crema abbronzante senza profumazione SPF 50+ (50 ml)",
    affiliateUrl: "https://www.notino.it/avene/sun-crema-abbronzante-spf-50/p-16122800/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770149494_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVESUNW_KFCR01",
    skinTypes: ["sensibile", "secca"],
    concerns: ["protezione-solare", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-photoderm-akn-mat",
    name: "Photoderm AKN Mat",
    brand: "Bioderma",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 13.9,
    description: "Lozione protettiva SPF 30 (40 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/photoderm-akn-mat-lozione-protettiva-spf-30/p-16124714/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129803691_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRPHNW_KPCR59",
    skinTypes: ["grassa", "mista"],
    concerns: ["protezione-solare", "acne-sebo"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-bioderma-sensibio-ar-cc",
    name: "Sensibio AR+ CC",
    brand: "Bioderma",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 21.42,
    description: "Cream SPF 50+ (40 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/sensibio-ar-cc-cream-spf-50/p-16357573/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129813447_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIROBII_JVWA01",
    skinTypes: ["sensibile"],
    concerns: ["protezione-solare", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-capital-soleil-anti-age-spf-50",
    name: "Capital Soleil Anti-Age SPF 50",
    brand: "Vichy",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 16.91,
    description: "Crema protettiva anti-age SPF 50 (50 ml)",
    affiliateUrl: "https://www.notino.it/vichy/ideal-soleil-anti-age-crema-protettiva-anti-age-spf-50/p-11634349/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875585231_01-o__5.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHIDAW_KPCR10",
    skinTypes: ["normale", "secca"],
    concerns: ["protezione-solare", "anti-age"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-ducray-melascreen-uv",
    name: "Melascreen UV",
    brand: "Ducray",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 19.7,
    description: "Lozione protettiva contro le macchie della pelle (50 ml)",
    affiliateUrl: "https://www.notino.it/ducray/melascreen-lozione-protettiva-contro-le-macchie-della-pelle/p-16178729/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770389272_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURMCEW_KSHA02",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["protezione-solare", "macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-isdin-fusion-water-spf-30",
    name: "Fusion Water SPF 30",
    brand: "ISDIN",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: false,
    price: 20.74,
    description: "Crema protettiva viso SPF 30 (50 ml)",
    affiliateUrl: "https://www.notino.it/isdin/fusion-water-crema-protettiva-viso-spf-30/p-16187230/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/isdin/8429420189423_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:ISDFOTW_KFCR15",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["protezione-solare"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-svr-sun-secure-extreme",
    name: "Sun Secure Extreme",
    brand: "SVR",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: false,
    price: 13.5,
    description: "Crema-gel giorno opacizzante SPF 50+ (50 ml)",
    affiliateUrl: "https://www.notino.it/svr/sun-secure-crema-gel-giorno-opacizzante-spf-50/p-16131254/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/svr/3662361002603_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:SVRPKQW_KHCR04",
    skinTypes: ["grassa", "mista"],
    concerns: ["protezione-solare", "acne-sebo"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-beauty-of-joseon-relief-sun-aqua-fresh",
    name: "Relief Sun Aqua-Fresh",
    brand: "Beauty of Joseon",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: true,
    price: 11.47,
    description: "Crema-gel protettiva SPF 50 (50 ml)",
    affiliateUrl: "https://www.notino.it/beauty-of-joseon/relief-sun-aqua-fresh-crema-gel-protettiva-spf-50/p-16281658/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/beauty_of_joseon/8809968130277_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BEJRESW_KFCR01",
    skinTypes: ["grassa", "mista"],
    concerns: ["protezione-solare"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-anua-invisible-matte-finish-sunscreen",
    name: "Invisible Matte Finish Sunscreen",
    brand: "Anua",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 17.51,
    description: "Crema abbronzante opacizzante viso SPF 50 (50 ml)",
    affiliateUrl: "https://www.notino.it/anua/invisible-matte-finish-sunscreen-crema-abbronzante-opacizzante-viso-spf-50/p-16395278/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/anua/8800307379517_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AUATAWV_JNCV10",
    skinTypes: ["grassa", "mista"],
    concerns: ["protezione-solare", "pori-dilatati"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-torriden-dive-in-moisture-sun-cream",
    name: "Dive In Moisture Sun Cream",
    brand: "Torriden",
    gender: "unisex",
    category: "creme",
    tier: "top",
    korean: true,
    price: 20.4,
    description: "Crema abbronzante viso effetto idratante SPF 50+ (60 ml)",
    affiliateUrl: "https://www.notino.it/torriden/dive-in-moisture-sun-cream-crema-abbronzante-viso-effetto-idratante/p-16394080/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/torriden/8809784603955_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:TRJVUSW_JSOZ12",
    skinTypes: ["secca", "normale"],
    concerns: ["protezione-solare", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-dr-althea-aqua-glowing-sunscreen",
    name: "Aqua Glowing Sunscreen",
    brand: "Dr. Althea",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: true,
    price: 13.17,
    description: "Crema protettiva viso per idratazione intensa SPF 50+ (45 ml)",
    affiliateUrl: "https://www.notino.it/dr-althea/aqua-glowing-sunscreen-crema-protettiva-viso-per-idratazione-intensa/p-16393426/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/dr_althea/8809447255972_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DTEELKF_BQOF26",
    skinTypes: ["secca", "normale"],
    concerns: ["protezione-solare", "idratazione"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-cosrx-aloe-soothing-sun-cream",
    name: "Aloe Soothing Sun Cream",
    brand: "COSRX",
    gender: "unisex",
    category: "creme",
    tier: "base",
    korean: true,
    price: 13.17,
    description: "Crema abbronzante SPF 50 (50 ml)",
    affiliateUrl: "https://www.notino.it/cosrx/aloe-crema-abbronzante-spf-50/p-15846639/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/cosrx/8809416470191_01-o__3.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:CSXALOW_KFCR10",
    skinTypes: ["sensibile"],
    concerns: ["protezione-solare", "rossori-sensibilita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-dermalogica-powerbright-spf-50",
    name: "PowerBright SPF 50",
    brand: "Dermalogica",
    gender: "unisex",
    category: "creme",
    tier: "premium",
    korean: false,
    price: 74.71,
    description: "Crema giorno illumiannte per pelli iperpigmentate SPF 50 (50 ml)",
    affiliateUrl: "https://www.notino.it/dermalogica/powerbright-trx-crema-giorno-illumiannte-per-pelli-iperpigmentate-spf-50/p-502762/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/dermalogica/666151031500_01-o__16.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DLOPOWW_KPCR10",
    skinTypes: ["secca", "grassa", "mista", "normale"],
    concerns: ["protezione-solare", "macchie-luminosita"],
    pregnancySafe: true,
    sensitiveSafe: true,
  },
  {
    id: "nt-vichy-dercos-anti-dandruff-per-capelli-g",
    name: "Dercos Anti-Dandruff per Capelli Grassi",
    brand: "Vichy",
    gender: "unisex",
    category: "shampoo",
    tier: "top",
    korean: false,
    price: 19.55,
    description: "Shampoo antiforfora per capelli normali e grassi (390 ml)",
    affiliateUrl: "https://www.notino.it/vichy/dercos-anti-dandruff-shampoo-antiforfora-per-capelli-normali-e-grassi/p-495453/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337871331290_01-o__19.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHDADW_KSHA31",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-vichy-dercos-anti-dandruff-per-capelli-s",
    name: "Dercos Anti-Dandruff per Capelli Secchi",
    brand: "Vichy",
    gender: "unisex",
    category: "shampoo",
    tier: "top",
    korean: false,
    price: 17.76,
    description: "Shampoo antiforfora per capelli secchi (390 ml)",
    affiliateUrl: "https://www.notino.it/vichy/dercos-anti-dandruff-shampoo-antiforfora-per-capelli-secchi/p-16324942/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875902847_01.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHEWTM_DDZZ03",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-ducray-kelual-squanorm-regulating-treatm",
    name: "Kelual Squanorm Regulating Treatment Shampoo Oily Dandruff",
    brand: "Ducray",
    gender: "unisex",
    category: "shampoo",
    tier: "base",
    korean: false,
    price: 12.24,
    description: "Shampoo contro la forfora grassa (200 ml)",
    affiliateUrl: "https://www.notino.it/ducray/squanorm-shampoo-contro-la-forfora-grassa/p-406733/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770396423_01-o__28.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURSQAW_KSHA12",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-ducray-kelual-squanorm-moisturizing-trea",
    name: "Kelual Squanorm Moisturizing Treatment Shampoo Dry Dandruff",
    brand: "Ducray",
    gender: "unisex",
    category: "shampoo",
    tier: "top",
    korean: false,
    price: 17.42,
    description: "Shampoo contro la forfora secca (400 ml)",
    affiliateUrl: "https://www.notino.it/ducray/squanorm-shampoo-contro-la-forfora-secca/p-16291492/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770396515_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURXQOW_KSHA01",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-ducray-kelual-ds-intensive-anti-dandruff",
    name: "Kelual DS Intensive Anti-Dandruff Treatment Shampoo",
    brand: "Ducray",
    gender: "unisex",
    category: "shampoo",
    tier: "base",
    korean: false,
    price: 15.55,
    description: "Shampoo intenso contro la forfora (100 ml)",
    affiliateUrl: "https://www.notino.it/ducray/kelual-ds-intensive-anti-dandruff-treatment-shampoo-shampoo-intenso-contro-la-forfora/p-16331241/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770400786_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURZBCK_BVUR01",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-vichy-dercos-psolution",
    name: "Dercos PSOlution",
    brand: "Vichy",
    gender: "unisex",
    category: "shampoo",
    tier: "base",
    korean: false,
    price: 15.55,
    description: "Shampoo ipoallergenico per cuoi capelluti con psoriasi (200 ml)",
    affiliateUrl: "https://www.notino.it/vichy/dercos-psolution-shampoo-ipoallergenico-per-cuoi-capelluti-con-psoriasi/p-16111419/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875787222_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHPSOW_KSHA30",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-la-roche-posay-kerium-ds-anti-dandruff",
    name: "Kerium DS Anti-Dandruff",
    brand: "La Roche-Posay",
    gender: "unisex",
    category: "shampoo",
    tier: "top",
    korean: false,
    price: 21.67,
    description: "Shampoo trattante contro la forfora (200 ml)",
    affiliateUrl: "https://www.notino.it/la-roche-posay/kerium-shampoo-contro-la-forfora/p-16275182/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/la-roche-posay/3337875911184_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:LRPQCQW_KSHM04",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-bioderma-node-ds",
    name: "Nodé DS+",
    brand: "Bioderma",
    gender: "unisex",
    category: "shampoo",
    tier: "top",
    korean: false,
    price: 19.7,
    description: "Shampoo lenitivo contro la forfora (125 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/node-ds-shampoo-lenitivo-contro-la-forfora/p-16182612/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3701129805060_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRNODW_KSHA18",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-bioderma-node-a-shampooning",
    name: "Nodé A Shampooning",
    brand: "Bioderma",
    gender: "unisex",
    category: "shampoo",
    tier: "base",
    korean: false,
    price: 14.02,
    description: "Shampoo lenitivo per cuoi capelluti sensibili (400 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/node-a-shampoo-lenitivo-per-cuoi-capelluti-sensibili/p-100793/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3401396545132_01-o__30.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRNOAW_KSHA20",
    hairConcerns: ["mantenimento"],
  },
  {
    id: "nt-bioderma-node-g-shampoo",
    name: "Nodé G Shampoo",
    brand: "Bioderma",
    gender: "unisex",
    category: "shampoo",
    tier: "base",
    korean: false,
    price: 15.72,
    description: "Shampoo per capelli grassi (400 ml)",
    affiliateUrl: "https://www.notino.it/bioderma/node-g-shampoo-per-capelli-grassi/p-101209/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/bioderma/3401579333501_01-o__29.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:BIRNOGW_KSHA20",
    hairConcerns: ["mantenimento"],
  },
  {
    id: "nt-ducray-extra-doux",
    name: "Extra-Doux",
    brand: "Ducray",
    gender: "unisex",
    category: "shampoo",
    tier: "base",
    korean: false,
    price: 10.62,
    description: "Shampoo protettivo per il lavaggio frequente dei capelli (400 ml)",
    affiliateUrl: "https://www.notino.it/ducray/extra-doux-shampoo-per-il-lavaggio-frequente-dei-capelli/p-82279/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770148282_01-o__23.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DUREXDW_KSHA10",
    hairConcerns: ["mantenimento"],
  },
  {
    id: "nt-ducray-anaphase-anti-hair-loss-anti-thin",
    name: "Anaphase+ Anti-Hair Loss Anti-Thinning Shampoo",
    brand: "Ducray",
    gender: "unisex",
    category: "shampoo",
    tier: "top",
    korean: false,
    price: 17.34,
    description: "Shampoo rinforzante e rivitalizzante anti-caduta dei capelli (400 ml)",
    affiliateUrl: "https://www.notino.it/ducray/anaphase-shampoo-rinforzante-e-rivitalizzante-anti-caduta-dei-capelli/p-610559/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770075526_01-o__15.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURAPPW_KSHA20",
    hairConcerns: ["caduta"],
  },
  {
    id: "nt-medicube-soyxidil-shampoo",
    name: "Soyxidil Shampoo",
    brand: "Medicube",
    gender: "unisex",
    category: "shampoo",
    tier: "top",
    korean: true,
    price: 21.93,
    description: "Shampoo trattante e rinforzante anti-caduta dei capelli (490 ml)",
    affiliateUrl: "https://www.notino.it/medicube/soyxidil-shampoo-shampoo-trattante-e-rinforzante-anti-caduta-dei-capelli/p-16359266/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/medicube/8800289479045_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:MCBKEVH_CQVW04",
    hairConcerns: ["caduta"],
  },
  {
    id: "nt-vichy-dercos-densi-solutions",
    name: "Dercos Densi Solutions",
    brand: "Vichy",
    gender: "unisex",
    category: "shampoo",
    tier: "base",
    korean: false,
    price: 16.9,
    description: "Shampoo addensante (250 ml)",
    affiliateUrl: "https://www.notino.it/vichy/dercos-densi-solutions-shampoo-addensante/p-645885/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875574358_01-o__11.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHDDSW_KSHA10",
    hairConcerns: ["caduta"],
  },
  {
    id: "nt-ducray-neoptide-expert",
    name: "Neoptide Expert",
    brand: "Ducray",
    gender: "unisex",
    category: "capelli",
    tier: "top",
    korean: false,
    price: 44.11,
    description: "Trattamento mirato anticaduta dei capelli per stimolare la crescita e rinforzare i capelli dalle radici 2x50 ml (50 ml)",
    affiliateUrl: "https://www.notino.it/ducray/neoptide-trattamento-mirato-anticaduta-dei-capelli/p-16156172/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770153255_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DUROGCW_KSHA03",
    hairConcerns: ["caduta"],
  },
  {
    id: "nt-vichy-dercos-serum-10",
    name: "Dercos Serum 10",
    brand: "Vichy",
    gender: "unisex",
    category: "capelli",
    tier: "top",
    korean: false,
    price: 35.61,
    description: "Cura trattante contro la forfora (90 ml)",
    affiliateUrl: "https://www.notino.it/vichy/dercos-serum-10-cura-trattante-contro-la-forfora/p-16276152/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875901420_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHDRCW_KSHA02",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-ducray-kelual-squanorm-fresh-control-lot",
    name: "Kelual Squanorm Fresh Control Lotion",
    brand: "Ducray",
    gender: "unisex",
    category: "capelli",
    tier: "base",
    korean: false,
    price: 13.43,
    description: "Soluzione contro la forfora (190 ml)",
    affiliateUrl: "https://www.notino.it/ducray/squanorm-soluzione-contro-la-forfora/p-95954/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770397499_01-o__26.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURSQAW_KTON10",
    hairConcerns: ["forfora"],
  },
  {
    id: "nt-ducray-anaphase-fortifying-anti-breakage",
    name: "Anaphase+ Fortifying Anti-Breakage Conditioner",
    brand: "Ducray",
    gender: "unisex",
    category: "capelli",
    tier: "base",
    korean: false,
    price: 15.47,
    description: "Balsamo rinforzante contro la rottura dei capelli (200 ml)",
    affiliateUrl: "https://www.notino.it/ducray/anaphase-balsamo-rinforzante-anti-caduta-dei-capelli/p-578439/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/ducray/3282770073683_01-o__18.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:DURAPPW_KCND10",
    hairConcerns: ["caduta", "secchi-crespi"],
  },
  {
    id: "nt-vichy-dercos-collagen-filler-17",
    name: "Dercos Collagen Filler 17",
    brand: "Vichy",
    gender: "unisex",
    category: "capelli",
    tier: "top",
    korean: false,
    price: 17.93,
    description: "Balsamo rigenerante intenso (200 ml)",
    affiliateUrl: "https://www.notino.it/vichy/dercos-collagen-filler-17-balsamo-rigenerante-intenso/p-16351318/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/vichy/3337875920971_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:VCHZKLB_YXDO03",
    hairConcerns: ["secchi-crespi"],
  },
  {
    id: "nt-avene-men-gel-da-rasatura",
    name: "Men Gel da Rasatura",
    brand: "Avène",
    gender: "uomo",
    category: "barba",
    tier: "base",
    korean: false,
    price: 13.17,
    description: "Gel per rasatura (150 ml)",
    affiliateUrl: "https://www.notino.it/avene/men-gel-per-rasatura/p-16143568/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282770147896_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVEXBTW_KECL01",
    beardConcerns: ["irritazione"],
  },
  {
    id: "nt-avene-men-balsamo-post-rasatura",
    name: "Men Balsamo Post-Rasatura",
    brand: "Avène",
    gender: "uomo",
    category: "barba",
    tier: "base",
    korean: false,
    price: 13.17,
    description: "Balsamo post-rasatura per pelli sensibili e secche (50 ml)",
    affiliateUrl: "https://www.notino.it/avene/men-balsamo-after-shave-per-pelli-sensibili-e-secche/p-16391133/",
    linkPending: true,
    image: "https://cdn.notinoimg.com/google/avene/3282771000947_01-o.jpg",
    merchant: "Notino",
    feedId: "cj:4917850:AVEBZME_BQBS01",
    beardConcerns: ["irritazione"],
  },
];
